# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
